### ISSUE TITLE
Need The text more dark theme

### ISSUE THREAD

**Issue by THEBOSS0369** [THEBOSS0369/EMI-Calculator#4]
The Text in the dark mode is Not visible Correctly . See the SS below
![image](https://github.com/user-attachments/assets/244c64dc-36d1-4597-8476-efe513744773)

**Comment by Kinshu-Learner** [comment]
Hi! I would like to work on this issue.

**Comment by Kinshu-Learner** [comment]
Also, it doesn't look like your repo is participating in hacktoberfest? Why do you have the hacktoberfest label on the issue then?

**Comment by THEBOSS0369** [comment]
eHey @Kinshu-Learner ! Thanks for contribution. But i don't think this repo will come in hactoberfest because i didn't knew that we had to sign up for the hacktoberfest. But still please check in your hacktoberfest profile that the pr you created is coming in hactoberfest or not, if its coming then great i will merge your pr as your pr has fixed the issue.
